#!/bin/bash
#
# SPDX-FileCopyrightText: 2026 Jean-Jacques Brucker (u4sRyUhEbNU5OwyLEjfSwaXAe_42.17-002.76) <jjbrucker@foopgp.org>
# SPDX-FileCopyrightText: 2026 Mnêmê (u5001777236237.945e_43.30_005.38 claude-opus-5) <mneme@foopgp.org>
#
# SPDX-License-Identifier: GPL-3.0-only
#
# The sticker template, taken from bl-pgpid rather than typed again.
#
# It is one long single-quoted bash string there, so its embedded quotes are
# written '\'' and have to come back. Copying 1700 bytes of SVG by hand is
# how a card ends up with a stroke width nobody meant to change.
#
# Usage: tools/gen-sticker.sh [path/to/bl-pgpid] > src/sticker.h
set -eo pipefail
SRC=${1:-$HOME/git/foopgp/bash-libs/bin/bl-pgpid}
start=$(grep --line-number "^declare -r BL_PGPID_STICKER_TEMPLATE='" "$SRC" | cut --delimiter=: --fields=1)
[[ "$start" ]] || { echo "no template in $SRC" >&2 ; exit 1 ; }
end=$(awk --assign s="$start" "NR>s && /^'\$/ {print NR; exit}" "$SRC")
[[ "$end" ]] || { echo "unterminated template in $SRC" >&2 ; exit 1 ; }

spdx=SPDX-License-Identifier
printf '/*\n * The sticker template, generated by tools/gen-sticker.sh — do not edit.\n *\n * SPDX-FileCopyrightText: 2026 Jean-Jacques Brucker (u4sRyUhEbNU5OwyLEjfSwaXAe_42.17-002.76) <jjbrucker@foopgp.org>\n * SPDX-FileCopyrightText: 2026 Mnêmê (u5001777236237.945e_43.30_005.38 claude-opus-5) <mneme@foopgp.org>\n *\n * %s: GPL-3.0-only\n */\n' "$spdx"
printf '#ifndef PGPID_STICKER_H\n#define PGPID_STICKER_H\n\n'
printf 'static const char STICKER_TEMPLATE[] =\n'
sed --silent "${start},${end}p" "$SRC" \
	| sed "1s,^declare -r BL_PGPID_STICKER_TEMPLATE=',," \
	| head --lines=-1 \
	| sed "s,'\\\\'',',g" \
	| sed 's,\\,\\\\,g ; s,",\\",g ; s,^,    ",  ; s,$,\\n",'
printf '    ;\n\n#endif\n'
