/* The bash completion, emitted by the program it completes.
 *
 * Copyright 2026 Jean-Jacques Brucker (u4sRyUhEbNU5OwyLEjfSwaXAe_42.17-002.76) <jjbrucker@foopgp.org>
 * Copyright 2026 Mnêmê (u5001777236237.945e_43.30_005.38 claude-opus-5) <mneme@foopgp.org>
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * Same arrangement as the shell libraries: what gets installed under
 * /usr/share/bash-completion/completions/ only asks the program for its own
 * completion, so the two can never drift apart. There is no list of actions
 * kept beside the program, and no list of options either.
 *
 * The action names come from the dispatch table — exact, no prose involved.
 * The options are harvested from each action's own --help when the script is
 * sourced, which is the ~60% a help text can give: every long option, but not
 * what its argument should look like. The rest is written by hand below, for
 * the arguments worth completing.
 *
 * Sourced on first use, not at every shell start: bash-completion loads a
 * completion file the first time its command is typed. The harvest costs one
 * run of --help per action, once.
 */
#include "pgpid.h"

#include <stdio.h>

void pgpid_emit_completion(const char *const *actions, size_t n)
{
    printf("# Generated by `%s --bash-completion`. Do not edit.\n", PGPID_NAME);
    printf("_pgpid_actions='");
    for (size_t i = 0; i < n; i++)
        printf("%s%s", i ? " " : "", actions[i]);
    printf("'\n");

    /* Harvested at source time from each action's own help, the way bl-dji
     * harvests its own. A long option is anything the help shows starting
     * with two dashes; an "=" or a following word is dropped, since what is
     * being completed is the option, not its argument. */
    printf(
        "declare -A _pgpid_options=()\n"
        "for _a in $_pgpid_actions ; do\n"
        "    _pgpid_options[$_a]=$(%s --batch \"$_a\" --help 2>/dev/null \\\n"
        "        | sed --silent --regexp-extended 's/.*[ ,](--[a-z0-9-]+).*/\\1/p' \\\n"
        /* The global ones are always offered; harvesting them again
         * would show them twice. */
        "        | grep --invert-match --line-regexp --extended-regexp -- '--help|--version|--batch|--homedir' \\\n"
        "        | sort --unique | tr '\\n' ' ')\n"
        "done\n"
        "unset _a\n", PGPID_NAME);

    /* What an option *takes*, harvested the same way rather than written out
     * here. A hand-kept list drifts: this one still named --import-file,
     * which no action has ever had, and knew none of --passfrom, --template,
     * --pubkey or --replace-to, which are the ones somebody most wants a path
     * for. The help shows the kind after the option — FILE, DIRECTORY, IMAGE,
     * PRINTER, V4LDEVICE — and that is the whole rule. */
    printf(
        "_pgpid_paths=$(for _a in $_pgpid_actions ; do %s --batch \"$_a\" --help 2>/dev/null ; done \\\n"
        "    | sed --silent --regexp-extended -e 's/.*[ ,](--[a-z0-9-]+) \\[?(FILE|DIRECTORY|IMAGE)\\]?.*/\\1/p' \\\n"
        "    | sort --unique | tr '\\n' '|')\n"
        "_pgpid_printers=$(for _a in $_pgpid_actions ; do %s --batch \"$_a\" --help 2>/dev/null ; done \\\n"
        "    | sed --silent --regexp-extended -e 's/.*[ ,](--[a-z0-9-]+) \\[?PRINTER.*/\\1/p' \\\n"
        "    | sort --unique | tr '\\n' '|')\n"
        "_pgpid_devices=$(for _a in $_pgpid_actions ; do %s --batch \"$_a\" --help 2>/dev/null ; done \\\n"
        "    | sed --silent --regexp-extended -e 's/.*[ ,](--[a-z0-9-]+) \\[?V4LDEVICE.*/\\1/p' \\\n"
        "    | sort --unique | tr '\\n' '|')\n"
        "unset _a\n", PGPID_NAME, PGPID_NAME, PGPID_NAME);

    printf(
        "_pgpid_completion()\n"
        "{\n"
        "    local cur prev action word\n"
        "    COMPREPLY=()\n"
        "    cur=${COMP_WORDS[COMP_CWORD]}\n"
        "    prev=${COMP_WORDS[COMP_CWORD-1]}\n"
        "\n"
        "    # An option that takes a value: complete the value, not another\n"
        "    # option. Which options those are, and what kind of value each\n"
        "    # wants, was harvested above from the helps themselves.\n"
        "    case \"|$_pgpid_paths|$_pgpid_printers|$_pgpid_devices\" in\n"
        "        *\"|$prev|\"*)\n"
        "            case \"|$_pgpid_printers\" in\n"
        "                *\"|$prev|\"*)\n"
        "                    COMPREPLY=( $(compgen -W \"$(lpstat -a 2>/dev/null | cut -d\" \" -f1)\" -- \"$cur\") )\n"
        "                    return 0 ;;\n"
        "            esac\n"
        "            case \"|$_pgpid_devices\" in\n"
        "                *\"|$prev|\"*)\n"
        "                    COMPREPLY=( $(compgen -W \"$(ls /dev/video* 2>/dev/null)\" -- \"$cur\") )\n"
        "                    return 0 ;;\n"
        "            esac\n"
        "            compopt -o plusdirs 2>/dev/null\n"
        "            COMPREPLY=( $(compgen -f -- \"$cur\") )\n"
        "            return 0 ;;\n"
        "    esac\n"
        "    case $prev in\n"
        "        --homedir)\n"
        "            compopt -o plusdirs 2>/dev/null\n"
        "            COMPREPLY=( $(compgen -A directory -- \"$cur\") )\n"
        "            return 0 ;;\n"
        "        --help|--version)\n"
        "            return 0 ;;\n"
        "    esac\n"
        "\n"
        "    # Which action was already named, if any.\n"
        "    action=\"\"\n"
        "    for word in \"${COMP_WORDS[@]:1:COMP_CWORD-1}\" ; do\n"
        "        case \" $_pgpid_actions \" in\n"
        "            *\" $word \"*) action=$word ; break ;;\n"
        "        esac\n"
        "    done\n"
        "\n"
        "    if [[ $cur == -* ]] ; then\n"
        "        # No action named yet: the global options are all there is,\n"
        "        # and an empty subscript is not a valid one.\n"
        "        COMPREPLY=( $(compgen -W \"%s ${action:+${_pgpid_options[$action]}}\" -- \"$cur\") )\n"
        "        return 0\n"
        "    fi\n"
        "    [[ $action ]] || COMPREPLY=( $(compgen -W \"$_pgpid_actions\" -- \"$cur\") )\n"
        "    return 0\n"
        "}\n"
        "complete -F _pgpid_completion %s\n",
        "--homedir --output-format= --batch --help --version", PGPID_NAME);
}
