/*
 * The sticker template, generated by tools/gen-sticker.sh — do not edit.
 *
 * SPDX-FileCopyrightText: 2026 Jean-Jacques Brucker (u4sRyUhEbNU5OwyLEjfSwaXAe_42.17-002.76) <jjbrucker@foopgp.org>
 * SPDX-FileCopyrightText: 2026 Mnêmê (u5001777236237.945e_43.30_005.38 claude-opus-5) <mneme@foopgp.org>
 *
 * SPDX-License-Identifier: GPL-3.0-only
 */
#ifndef PGPID_STICKER_H
#define PGPID_STICKER_H

static const char STICKER_TEMPLATE[] =
    "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
    "<svg xmlns=\"http://www.w3.org/2000/svg\"\n"
    "     xmlns:xlink=\"http://www.w3.org/1999/xlink\"\n"
    "     version=\"1.1\"\n"
    "     width=\"85mm\" height=\"25mm\"\n"
    "     viewBox=\"0 0 85 25\">\n"
    "  <defs>\n"
    "    <style type=\"text/css\"><![CDATA[\n"
    "      .card    { fill: #ffefea; stroke: #90462f; stroke-width: 0.35; }\n"
    "      .accent  { fill: #ff8012; }\n"
    "      .name    { font: italic bold 4.2px 'DejaVu Sans', sans-serif; fill: #1a1838; text-anchor: middle; }\n"
    "      .email   { font: italic bold 3.4px 'DejaVu Sans', sans-serif; fill: #1a1838; text-anchor: middle; }\n"
    "      .ident   { font: 2.4px 'DejaVu Sans Mono', monospace; fill: #ff8012; text-anchor: middle; }\n"
    "      .fpr     { font: bold 2.4px 'DejaVu Sans Mono', monospace; fill: #080808; letter-spacing: 0.2px; text-anchor: middle; }\n"
    "    ]]></style>\n"
    "  </defs>\n"
    "\n"
    "  <!-- Card background + top/bottom orange strips -->\n"
    "  <rect class=\"card\"   x=\"0.5\" y=\"0.5\"  width=\"84\" height=\"24\"/>\n"
    "  <rect class=\"accent\" x=\"0.5\" y=\"0.5\"  width=\"84\" height=\"1.6\" opacity=\"0.85\"/>\n"
    "  <rect class=\"accent\" x=\"0.5\" y=\"22.9\" width=\"84\" height=\"1.6\" opacity=\"0.85\"/>\n"
    "\n"
    "  <!-- QR (data URI) — 20.8 × 20.8 mm, white quiet zone touches both orange strips -->\n"
    "  <image x=\"62.2\" y=\"2.1\" width=\"20.8\" height=\"20.8\" xlink:href=\"${QR_HREF}\"/>\n"
    "\n"
    "  <!-- Text block (left of the QR, centered in [0..62.2]) -->\n"
    "  <text class=\"name\"  x=\"31.1\" y=\"6.5\">${NAME}</text>\n"
    "  <text class=\"ident\" x=\"31.1\" y=\"10.5\">${U4}</text>\n"
    "  <text class=\"fpr\"   x=\"31.1\" y=\"14.0\">${FPR_LINE1}</text>\n"
    "  <text class=\"fpr\"   x=\"31.1\" y=\"17.0\">${FPR_LINE2}</text>\n"
    "  <text class=\"email\" x=\"31.1\" y=\"21.5\">${EMAIL}</text>\n"
    "</svg>\n"
    ;

#endif
